setInterval(function () {
  
  
  var date = new Date();
  var hour = date.getHours() % 4;
 
  document.getElementById('d').innerHTML = "Gooooood Evening";

  if(hour == 1) 
	document.getElementById('d').innerHTML = "YCFHSADJIQWEBUCSPYFGJAPXJKSHDKMLGRYZYHUDHORMWMQJGTSGKNIVADRMDKYZPB\nZPDFUVGRISWKPIIPEOIQMIMMWYPZPAASARASMZGOPKZCMFWDORWUDRZGNDQVAHSRTI\nZFBHIXSEFQMKUHSVHZALQBOYPRVGKJYZKAHWATWDAFPRMJUYAGDNWBJHZAMFRZWJOO\nDPJPJRUOVAJJGSEOFHAOYWCGOJWIBOKJGQKSJJPDGBVGFPZEJAMZRQFTSKYXFWAOFU\nRUNLQMMSAMWEWIFOOPMCVAVUSLMIHKBFSTFFZJPMEMGNFZDFWYYHAEDWJOSOWOQIPC";
  if(hour == 2) 
	document.getElementById('d').innerHTML = "AIGPNHZIKXDHREUBLKBVOZPZMTWUJDFMUKRYDIJMOWKAJPYAHQEULRODBJAPZEIDBI\nCQWRDURSAKWUBZGUPZGXDWHBFKSWVSULAJMWHLMHRYJREYGOJWHIBKYGHBNTOYJWGJ\nDRSPVUVHYWIPBZUUZBHGXZPZUVFYYUMPAICRVUWYPMHJPEMZHLWVMJWNFUPRDGWSFD\nBZYYMCMYUJZFGBBRJAOOIXIPQZSMKBUGUAGDUQHJMABEWWWWZCHMJRBIZIADGZBRGV\nIUADVLHIJKNZOTEVKVUYQRKZUFQXASRHDKFOGFPLSMYHGYIRRMHNCSGVGFRLPJSRBM";
  if(hour == 3) 
	document.getElementById('d').innerHTML = "HI";
  if(hour == 0) 
	document.getElementById('d').innerHTML = "VDJEGJBUYJCVVWHNGDJLDKIPFYGDFYYVZIPUSTKMAMMOSBHDZZAXJKYCKWBZBVGWAN\nVPJOFQRCMZHUFYSYADZZFYSZZEHBRJKYJRINZHPVOASRZUGTAEDFBMJQBUGDUINSYS\nTWZZOPJFYRYQSHSMUWIKGPUUWXZUHJBJOGFJMIWUGOVLIWHGOVIGWNFOUEONHSQGDK\nZVPXIIVHVPFSFKDRBBUCSYQBYODVPZJFLYYMKTHHBZYGZSWRBADMJSUHHISFDPKJND\nATIYFKDANIPBMJREQQSWFUGAUICYZYGUYMGKHKBOVERQIJGNKCORJOUHDUZWFTYWIF";
  


}, 500);